baseurl = "https://jpena.dev"
title = "jpena.dev"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
    pagerSize = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "jpena-dev"

[params]
    author = "Hi! I'm John"
    info = "I am a Site Reliability Engineer @Udemy"
    description = "My blog"
    keywords = "blog,developer,personal"
    # avatarurl = "images/me.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = []

    colorscheme = "light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jpenagg/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/jpenagg/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/jpena23/"
[[params.social]]
    name = "Mail"
    icon = "far fa-envelope fa-2x"
    weight = 3
    url = "mailto:jsp3na@gmail.com"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "/files/jpena_cv.pdf"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
